### ISSUE TITLE
How to use this library ???

### ISSUE THREAD

**Issue by josuejcalazans** [m-adamski/symfony-notification-bundle#1]
Could you explain how to use the library for notification?

**Comment by m-adamski** [comment]
Hi Josue,

I'm very pleased that you are interested in using this library.
Suppose you want to display a notification after creating a user account. To do this, you can call the ``routeRedirectNotification`` function from your controller.

```
return $this->notificationHelper->routeRedirectNotification(
	"account.create",
	NotificationHelper::SUCCESS_TYPE,
	$this->translator->trans("The account has been successfully created.", [], "account")
);
```

This will generate and return the RedirectResponse to the ``account.create`` route.

You must remember to put ``{{ notification() }}`` in your template - This function will generate HTML:

```
<section class="invisible" data-notification="The account has been successfully created."
	data-notification-type="success">
</section>
```
Personally, I use the [noty](https://ned.im/noty/#/) JS library to display notifications but you can use this library in a different way.

You can also overwrite this template by creating ``notification.html.twig`` file in ``src/templates/bundles/NotificationBundle``
